In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Create SQLAlchemy connection (change username, password, host, dbname)
engine = create_engine("mysql+pymysql://root:dharma@localhost:3306/supply_chain_management_system")

# Read SQL query from file
with open("C:/Users/Dharm/AppData/Roaming/DBeaverData/workspace6/General/Scripts/Script-1.sql", "r") as file:
    sql_query = file.read()

sql_query_1="select * from Warehouses;"

# Execute query and load into DataFrame
df = pd.read_sql_query(sql_query, engine)
df

,supplierName,contactName,phone,email
0,Stark Inc,Kevin Rodriguez,257-276-9787,blake45@example.com
1,Klein-Klein,Amanda Miller,964.778.5271,jones.amy@example.org
2,Parker Group,James Young,983.582.7414,christinegreer@example.org
3,Watson Inc,Andrew Anderson,888-216-1192x2701,hansenmegan@example.com
4,Howard-Boyd,Elizabeth Nelson,(313)213-9073,ramirezsteven@example.org
5,"Ramos, Campbell and Vargas",Samantha Miller,786-929-0557,jonesscott@example.org
6,Kennedy Group,Stephanie Flores,939.451.6824x7066,grahambryan@example.net
7,Walton Inc,David Gonzalez,(902)375-3644x278,angelicacantu@example.com
8,Douglas and Sons,Daniel Anderson,192.086.6247x080,christinerojas@example.org
9,Nguyen PLC,Jennifer Smith,241-603-2514,rwillis@example.net
10,Gonzalez LLC,Rachel Carter,814.487.9680,twhite@example.org
11,Nelson LLC,Thomas Garcia,630-012-1462x9185,ricemargaret@example.com
12,"Mendoza, Parker and Wilson",Brian Clark,(853)078-9529,stevensmarcus@example.net
13,Sullivan Ltd,Christina Johnson,662.348.3960,rbarnes@example.net
14,Gomez and Sons,Rebecca Thomas,034-264-8475,martindeborah@example.org
15,"Barnes, King and Grant",Jeffrey Davis,(351)880-6945,ryan79@example.com
16,Walsh-Jones,Anthony Adams,850-079-1804,josephmoore@example.org
17,"Fields, Harris and Lambert",Nicholas Lee,(592)496-0971x3423,kennethrobinson@example.net
18,"Ramirez, May and Lambert",Ashley Scott,312.670.9616,darren73@example.net
19,"Brady, Stevens and Harris",Jessica Martinez,(681)356-2754,michael24@example.com

In [2]:
sql_query_1="select * from Warehouses;"
sql_data=pd.read_sql(sql_query_1,engine)
sql_data

    WarehouseID             WarehouseName                             Location
0             1       Lake John Warehouse      East Zacharyport, United States
1             2   West Brittany Warehouse           East Amanda, United States
2             3       New Sarah Warehouse          Port Tiffany, United States
3             4    Port Lindsay Warehouse             West Ryan, United States
4             5      Port Tanya Warehouse      Port Crystalfort, United States
5             6     Port Donald Warehouse           Port Rodney, United States
6             7    Port Matthew Warehouse          South Victor, United States
7             8     Lake Andrew Warehouse           Port Daniel, United States
8             9     North Scott Warehouse           Lake Amanda, United States
9            10     South Brian Warehouse      North Crystalton, United States
10           11      Lake Bryan Warehouse             West Dana, United States
11           12       New Randy Warehouse            Lake Robin, United States
12           13  South Lawrence Warehouse           Lake Denise, United States
13           14       New Craig Warehouse          Lake Randall, United States
14           15   South Richard Warehouse          Port Matthew, United States
15           16       Lake Todd Warehouse  East Christopherbury, United States
16           17  West Christine Warehouse           Port Monica, United States
17           18     Lake Daniel Warehouse         North Natalie, United States
18           19     Lake Sharon Warehouse        South Brittany, United States
19           20    Lake Natasha Warehouse       Port Sarahville, United States